fix problems add some info in log

diff --git a/tensorflow_cc/cmake/build_tensorflow.sh.in b/tensorflow_cc/cmake/build_tensorflow.sh.in
--- a/tensorflow_cc/cmake/build_tensorflow.sh.in
+++ b/tensorflow_cc/cmake/build_tensorflow.sh.in
@@ -6,9 +6,11 @@ function version_gt {
     test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"
 }
 
-#function check_bazel_version {
-#	 [ "$(bazel version 2>/dev/null | grep 'Build label' | cut -f3 -d' ')" == 0.26.1 ] && echo bazel ok
-#}
+function check_bazel_version {
+    [ "$(bazel version 2>/dev/null | grep 'Build label' | cut -f3 -d' ')" == 0.26.1 ] || (echo "Bazel version 0.26.1 not found and bazelisk is not supported." && exit 1)
+}
+
+check_bazel_version
 
 # configure environmental variables
 export CC_OPT_FLAGS=${CC_OPT_FLAGS:-"-march=native"}
@@ -39,10 +41,14 @@ export PYTHON_LIB_PATH="$($PYTHON_BIN_PATH -c 'import site; print(site.getsitepa
 export bazel_local_cpu_resources="@BAZEL_LOCAL_CPU_RESOURCES@"
 export bazel_javacopt="@BAZEL_JAVACOPT_CACHE_MIN@ @BAZEL_JAVACOPT_CACHE_MAX@"
 export bazel_jvmopt="@BAZEL_JVMOPT_CACHE_MIN@ @BAZEL_JVMOPT_CACHE_MAX@"
-export bazel_version="0.26.1"
 
-# remove warnings that clutter up the log
-export c_cxx_no_warn="--cxxopt=-Wno-unused-result --cxxopt=-Wno-ignored-attributes --cxxopt=-Wno-maybe-uninitialized --cxxopt=-Wno-sign-compare --cxxopt=-Wno-return-type --cxxopt=-Wno-deprecated-declarations --cxxopt=-fPIC --cxxopt=-std=gnu++11 --cxxopt=-Wno-ignored-attributes --copt=-Wno-comment --copt=-Wno-unused-function --copt=-Wno-maybe-uninitialized --copt=-Wno-unused-result --copt=-Wno-deprecated-declarations --copt=-march=native --copt=-Wno-sign-compare --copt=-Wno-unknown-pragmas --copt=-Wno-unused-but-set-parameter --copt=-Wno-return-type --copt=-O3 --copt=-fPIC"
+# remove warnings that clutter up the bazel output
+export c_cxx_no_warn=""
+if [ "@BAZEL_IGNORE_WARNINGS@" = "ON" ]
+then
+    echo "Ignore warnings generated by Tensorflow compile"
+    export c_cxx_no_warn="--cxxopt=-Wno-strict-aliasing --cxxopt=-Wno-unused-result --cxxopt=-Wno-ignored-attributes --cxxopt=-Wno-maybe-uninitialized --cxxopt=-Wno-sign-compare  --cxxopt=-Wno-ignored-attributes --cxxopt=-Wno-return-type --cxxopt=-Wno-deprecated-declarations --cxxopt=-fPIC --cxxopt=-std=gnu++11 -copt=-Wno-implicit-function-declaration --copt=-Wno-comment --copt=-Wno-unused-function --copt=-Wno-maybe-uninitialized --copt=-Wno-unused-result --copt=-Wno-deprecated-declarations --copt=-march=native --copt=-Wno-sign-compare --copt=-Wno-unknown-pragmas --copt=-Wno-unused-but-set-parameter --copt=-Wno-parentheses --copt=-Wno-return-type --copt=-O3 --copt=-fPIC"
+fi
 
 # check if cuda support requested and supported
 if [ "@ALLOW_CUDA@" = "ON" ] && hash nvcc 2>/dev/null; then
@@ -87,19 +93,15 @@ fi
 
 # configure and build
 ./configure
-echo "USE_BAZEL_VERSION=${bazel_version} bazel build --config=opt --config=monolithic ${c_cxx_no_warn} ${bazel_local_cpu_resources} ${bazel_javacopt} ${bazel_jvmopt} ${cuda_config_opts} tensorflow:libtensorflow_cc.so"
-USE_BAZEL_VERSION=${bazel_version} bazel build --config=opt \
+export bazel_build_line="bazel build --config=opt --config=monolithic ${c_cxx_no_warn} ${bazel_local_cpu_resources} ${bazel_javacopt} ${bazel_jvmopt} ${cuda_config_opts} tensorflow:libtensorflow_cc.so"
+bazel build --config=opt \
             --config=monolithic \
-            ${c_cxx_no_warn} \
-            ${bazel_local_cpu_resources} \
-            ${bazel_javacopt} \
-            ${bazel_jvmopt} \
-            ${cuda_config_opts} \
-            tensorflow:libtensorflow_cc.so
-if [ $? -ne 0 ]
-then
-	echo "bazel build failed"
-else
+            "${c_cxx_no_warn}" \
+            "${bazel_local_cpu_resources}" \
+            "${bazel_javacopt}" \
+            "${bazel_jvmopt}" \
+            "${cuda_config_opts}" \
+            tensorflow:libtensorflow_cc.so || ( printf "Bazel build failed\ncommand line is\n\t%s\n\n" "${bazel_build_line}" && exit 1)
 cat <<- build_artifacts_location
 Tensorflow build succeeded
 
@@ -117,6 +119,7 @@ Build artifacts:
 	additional header directories required. All of these should be under
 		tensorflow/bazel-tensorflow
 		tensorflow/bazel-genfiles
+
+    If they are not found in these directories, use "find" and send a PR.
 build_artifacts_location
-fi
 bazel shutdown
