colorize output and add bazel variables

diff --git a/tensorflow_cc/cmake/build_tensorflow.sh.in b/tensorflow_cc/cmake/build_tensorflow.sh.in
--- a/tensorflow_cc/cmake/build_tensorflow.sh.in
+++ b/tensorflow_cc/cmake/build_tensorflow.sh.in
@@ -37,19 +37,19 @@ export PYTHON_BIN_PATH=${PYTHON_BIN_PATH:-"$(which python3)"}
 export PYTHON_LIB_PATH="$($PYTHON_BIN_PATH -c 'import site; print(site.getsitepackages()[0])')"
 
 ## should this project build OpenBLAS and install in /usr/local?
-#OPENBLAS_SRC_PATH=/tmp/openblas_src/
-#sudo rm -rf ${OPENBLAS_SRC_PATH}
-#git clone https://github.com/xianyi/OpenBLAS ${OPENBLAS_SRC_PATH}
-#cd ${OPENBLAS_SRC_PATH}
-## The commit after this introduced Fortran compile issues. In theory they should
-## be solvable using NOFORTRAN=1 on the make command, but my initial tries didn't
-## work, so pinning to the last know good version.
-#git checkout 5a6a2bed9aff0ba8a18651d5514d029c8cae336a
-## If this path is changed, you'll also need to update
-## cxx_builtin_include_directory in third_party/toolchains/cpus/arm/CROSSTOOL.tpl
-#OPENBLAS_INSTALL_PATH=/tmp/openblas_install/
-#make CC=${CROSSTOOL_CC} FC=${CROSSTOOL_CC} HOSTCC=gcc TARGET=ARMV6
-#make PREFIX=${OPENBLAS_INSTALL_PATH} install
+OPENBLAS_SRC_PATH=/tmp/openblas_src/
+sudo rm -rf ${OPENBLAS_SRC_PATH}
+git clone https://github.com/xianyi/OpenBLAS ${OPENBLAS_SRC_PATH}
+cd ${OPENBLAS_SRC_PATH}
+# The commit after this introduced Fortran compile issues. In theory they should
+# be solvable using NOFORTRAN=1 on the make command, but my initial tries didn't
+# work, so pinning to the last know good version.
+git checkout 5a6a2bed9aff0ba8a18651d5514d029c8cae336a
+# If this path is changed, you'll also need to update
+# cxx_builtin_include_directory in third_party/toolchains/cpus/arm/CROSSTOOL.tpl
+OPENBLAS_INSTALL_PATH=/tmp/openblas_install/
+make CC=${CROSSTOOL_CC} FC=${CROSSTOOL_CC} HOSTCC=gcc TARGET=ARMV6
+make PREFIX=${OPENBLAS_INSTALL_PATH} install
 
 export bazel_n_jobs="--jobs=@BAZEL_N_JOBS@"
 export bazel_local_resources="--local-resources=@BAZEL_LOCAL_RESOURCES@"
@@ -113,8 +113,6 @@ else
     export TF_NEED_CUDA=0
 fi
 
-#            --local_resources 1024,0.5,0.5 \
-
 # configure and build
 ./configure
 bazel build --config=opt \
@@ -128,4 +126,27 @@ bazel build --config=opt \
             ${tensorflow_pi_opts} \
             $cuda_config_opts \
             tensorflow:libtensorflow_cc.so
+if [ $? -ne 0 ]
+then
+	echo "bazel build failed"
+else
+cat <<- build_artifacts_location
+Tensorflow build succeeded
+
+Build artifacts:
+	Library
+		libtensorflow_cc.so is in tensorflow/bazel-bin/tensorflow
+
+	Header files
+		tensorflow/bazel-tensorflow/external/com_google_absl
+		tensorflow/bazel-tensorflow/external/eigen_archive
+		tensorflow/bazel-tensorflow/external/protobuf_archive/src
+		tensorflow/bazel-genfiles
+	
+	Note that due to changes in the Tensorflow project, there may be
+	additional header directories required. All of these should be under
+		tensorflow/bazel-tensorflow
+		tensorflow/bazel-genfiles
+build_artifacts_location
+fi
 bazel shutdown
